# The name of our workflow
name: Deploy Website to GCP

# Define when this workflow runs
on:
  push:
    branches:
      - main # The workflow will run on every push to the main branch

# The jobs that make up the workflow
jobs:
  deploy:
    # The environment to run the job on
    runs-on: ubuntu-latest

    # The steps the job will execute
    steps:
      # Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using the service account key stored in GitHub Secrets
      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Install Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize Terraform (fetches providers and sets up backend)
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      # Apply the Terraform configuration to provision the GCS bucket
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/

      # Sync the website files to the newly created GCS bucket
      - name: Upload website to Cloud Storage
        run: gcloud storage cp -r website/* gs://the-world-shall-know-pain/
